export const disclaimerCopy = {
  globalPlatform:
    'Currenc Intelligence provides market intelligence, data analytics, and AI-assisted insights for informational purposes only. Information presented on this platform should not be construed as investment advice, legal advice, accounting advice, tax advice, or a recommendation to buy, sell, hold, or otherwise transact in any security or financial instrument. Users remain solely responsible for their own investment, trading, legal, tax, and business decisions.',
  aiAnalysis:
    'Certain summaries, scores, alerts, explanations, and scenario analyses may be generated or assisted by artificial intelligence models together with proprietary analytical rules and market data. AI-generated content may contain inaccuracies, omissions, delayed interpretations, or incomplete context. Users should independently verify all AI-assisted outputs before relying on them.',
  marketData:
    'Market data may be sourced from public filings, exchanges, regulatory databases, third-party data providers, licensed vendors, and internal calculations. Data availability, update frequency, reporting delays, vendor revisions, and source limitations may affect displayed metrics. Currenc Intelligence does not guarantee the completeness, accuracy, timeliness, or reliability of any market data.',
  proprietaryScore:
    'Scores displayed on the platform are proprietary analytical indicators developed to summarize multiple market variables. These scores are not official market ratings, exchange-calculated figures, regulatory determinations, or factual guarantees. Scores should be interpreted as directional analytical tools, not as standalone decision-making signals.',
  alert:
    'Custom alerts are generated based on predefined rules and/or user-defined thresholds. A triggered alert only indicates that selected conditions have been met. The absence of an alert does not imply the absence of market risk, trading risk, regulatory risk, liquidity risk, or operational risk. Alerts should not be interpreted as investment recommendations or instructions to take action.',
  forecast:
    'Forecasts, probability estimates, price scenarios, risk scenarios, and forward-looking analytics are hypothetical and model-derived. They are based on assumptions, historical data, statistical patterns, and available market information. They do not represent guarantees, predictions, or assurances of future performance or outcomes.',
  regulatoryFiling:
    'Ownership, insider activity, institutional holdings, short interest, fail-to-deliver data, and other regulatory filing-based information may be delayed, amended, incomplete, or subject to reporting thresholds and filing rules. Such information may not reflect current real-time positions or intentions of market participants.',
  securitiesLending:
    'Borrow fee, utilization, available shares, on-loan shares, lending pressure, and related securities lending metrics may be estimates or derived from third-party lending market data. These metrics may not represent the full market and may differ across brokers, custodians, lending agents, and data vendors.',
  optionsGamma:
    'Options analytics, gamma exposure, delta exposure, implied volatility interpretation, and related derivatives metrics may be model-derived estimates. They may rely on assumptions including pricing models, open interest, volatility inputs, and market data availability. These outputs are not exchange-certified calculations.',
  internalFloat:
    'Tradable float, real float, internal float, tokenized shares, locked shares, pledged shares, and related ownership calculations may include user-defined assumptions, company-provided inputs, public filings, blockchain data, and proprietary calculations. These figures should not be treated as official share counts unless explicitly stated.',
  report:
    'Reports generated by Currenc Intelligence are prepared using market data, public information, licensed or third-party data sources, proprietary analytics, and AI-assisted technologies. Reports are provided solely for informational purposes and do not constitute investment research, investment advice, solicitation, or an offer to buy or sell any security. Users should perform independent due diligence and consult qualified professional advisors before making decisions.',
} as const;

export type DisclaimerKey = keyof typeof disclaimerCopy;

export const fullDisclaimerSections: Array<{
  id: string;
  title: string;
  disclaimerKey: DisclaimerKey;
}> = [
  { id: 'platform-use', title: 'Platform Use', disclaimerKey: 'globalPlatform' },
  { id: 'ai-assisted-analysis', title: 'AI-Assisted Analysis', disclaimerKey: 'aiAnalysis' },
  { id: 'market-data', title: 'Market Data', disclaimerKey: 'marketData' },
  { id: 'proprietary-scores', title: 'Proprietary Scores', disclaimerKey: 'proprietaryScore' },
  { id: 'custom-alerts', title: 'Custom Alerts', disclaimerKey: 'alert' },
  { id: 'forecasts-scenarios', title: 'Forecasts & Scenarios', disclaimerKey: 'forecast' },
  { id: 'regulatory-filings', title: 'Regulatory Filings', disclaimerKey: 'regulatoryFiling' },
  { id: 'securities-lending', title: 'Securities Lending Data', disclaimerKey: 'securitiesLending' },
  { id: 'options-gamma', title: 'Options & Gamma Analytics', disclaimerKey: 'optionsGamma' },
  { id: 'internal-float', title: 'Internal Float & Tokenized Shares', disclaimerKey: 'internalFloat' },
  { id: 'reports', title: 'Reports', disclaimerKey: 'report' },
];

export const footerDisclaimer =
  'AI-assisted market intelligence. Not investment advice. Market data may be delayed or incomplete.';

export const finalDisclaimerAcknowledgement =
  'By using Currenc Intelligence, users acknowledge that the platform is an analytical decision-support tool and not a substitute for independent professional judgment.';

export const pageDisclaimerNotices = {
  dashboard:
    'Dashboard insights may include AI-assisted summaries, proprietary scores, and delayed market data.',
  shortInterest:
    'Short interest metrics may be delayed and may depend on exchange, regulatory, or third-party reporting schedules.',
  lendingPressure:
    'Borrow fee, utilization, on-loan shares, and available shares may be estimates derived from securities lending market data.',
  ownership:
    'Institutional ownership and insider activity are based on regulatory filings and may not reflect current real-time holdings.',
  insider:
    'Insider activity reflects public filings and may be subject to reporting delays, amendments, and filing thresholds.',
  options:
    'Options and gamma analytics are model-derived estimates and may depend on assumptions, open interest, volatility, and pricing data.',
  internalFloat:
    'Real tradable float calculations may include user-defined assumptions and should not be treated as official share counts.',
  reports:
    'Reports are informational decision-support materials and do not constitute investment research or investment advice.',
  scenarios:
    'Price and risk scenarios are hypothetical, model-derived outcomes and are not predictions or guarantees of future performance.',
  scores:
    'Displayed scores are proprietary directional indicators and should not be used as standalone decision-making signals.',
  alert:
    'Custom alerts are based on user-defined thresholds and available market data. A triggered alert does not constitute investment advice, and the absence of an alert does not mean risk is absent.',
} as const;

export type PageDisclaimerNoticeKey = keyof typeof pageDisclaimerNotices;

export const methodologyContent = {
  dataSources: [
    'SEC filings',
    'FINRA data',
    'Exchange and market data',
    'Securities lending data providers',
    'Options and derivatives data providers',
    'Public company disclosures',
    'Blockchain data where applicable',
    'Internal user-defined assumptions',
  ],
  updateFrequency:
    'Different datasets update at different frequencies. Some metrics may be real-time or near real-time, while others may update daily, biweekly, monthly, quarterly, or only when regulatory filings are published.',
  proprietaryCalculations:
    'Certain indicators, scores, rankings, and alerts are calculated using proprietary formulas and rule-based logic. These outputs are designed to support analysis and should not be treated as official market statistics.',
  aiUsage:
    'AI may be used to summarize, explain, classify, compare, and generate scenario-based interpretations from available data. AI is not used as a guarantee of accuracy or outcome.',
} as const;

export const reportFooterDisclaimer =
  'For informational purposes only. Not investment advice. Market data and AI-assisted analysis may be inaccurate, delayed, or incomplete.';

export const reportFullDisclaimer =
  'This report has been prepared by Currenc Intelligence using proprietary analytics, public information, third-party market data, and AI-assisted technologies. It is provided solely for informational purposes and does not constitute investment advice, legal advice, tax advice, accounting advice, investment research, solicitation, or an offer to buy or sell any security. Currenc Intelligence does not guarantee the completeness, accuracy, timeliness, or reliability of any data, analysis, score, forecast, scenario, or alert contained in this report. Users should perform independent due diligence and consult qualified professional advisors before making decisions. Past performance does not guarantee future results.';
